name: Generate Snake Animation

on:
  # Uruchamia się automatycznie każdego dnia o 00:00 UTC
  schedule:
    - cron: "0 0 * * *"
  
  # Możliwość uruchomienia ręcznego
  workflow_dispatch:
  
  # Uruchamia się przy każdym push do main branch
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Generuje snake animation z Twoich contributions
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Adam903PL  # ← ZMIEŃ NA SWOJĄ NAZWĘ UŻYTKOWNIKA
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      
      # Publikuje wygenerowane pliki
      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
